### ISSUE TITLE
[BUG] Incorrect armor rendering when running on Linux

### ISSUE THREAD

**Issue by H4kt** [oraxen/oraxen#1098]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I was setting up Oraxen locally to prepare the update for my server.
Armor set configuration is attached below.

While testing locally (running server on my windows machine) everithing seems to work fine
![image](https://github.com/oraxen/oraxen/assets/50774419/f9298f87-79b7-49fa-8137-295a10e552ce)

However when I've uploaded the same configuration to my production server (running on Linux) armor rendering completely broke.
![image](https://github.com/oraxen/oraxen/assets/50774419/64d6b577-3ab9-4355-94c0-3ddd7991e3b3)

I've repeated the same test on a test server which was set up on the same machine as my production server and the issue persists.

### Steps to reproduce

Setup a paper server on a linux machine
Install Oraxen and let it generate default configuration files
Install the attached armor set
Set `pack.armor_resolution` to 32
Restart the server
Equip the armor set

### Plugin Version

1.163.0

### ProtocolLib Version

5.1.0

### Server Software & Version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Sadly im not able to bugtest oraxen on a linux machine atm
I doubt this is solely due to server being on Linux as 90% of servers with Oraxen is using Linux: https://bstats.org/plugin/bukkit/Oraxen/5371

If the client is exactly the same then I am not sure, check the leather_layer files in the pack.zip and compare them on your linux and windows(?) server

Please do not share premium assets without the original creators permission
As this looks like an armor set ive seen on MCModels and such sites

**Comment by H4kt** [comment]
> Please do not share premium assets without the original creators permission. As this looks like an armor set ive seen on MCModels and such sites
Sorry about that, thought you might need them to investigate. (btw we bought these)

The `leather_layer` files are identical. At least in the pack/textures/models folder. The `pack.zip` archive is somehow protected and I don't really know how to open it.

**Comment by Boy0000** [comment]
1. the pack.zip is protected and encrypted because Pack.protection is enabled in settings.yml
2. Bought or not, sharing them publically is not allowed as I and others probably dont own them

as mentioned, 90% of servers use oraxen are on linux so this is most likely a configuration issue and you should use the support discord for it

**Comment by H4kt** [comment]
> a configuration issue
I really doubt it because configuration is the same on both machines.
Anyway I'll try contacting the support on discord

**Comment by H4kt** [comment]
Contacted support on Discord.
They've double-checked my config files. Said they're all fine and that they have no idea why does the armor render like tha. Has to be a bug after all.

**Comment by Boy0000** [comment]
As mentioned before, 90% of servers run on Linux, so that is not the issue
Neither does that make sense as the armor-layer files generate the same
Then my only guess is your client but i cant replicate this issue at all

Not much I can doi here sadly as it seems to be an issue that noone else can reproduce but you
and no clear reason why it would not work

**Comment by H4kt** [comment]
Updating to the latest version of Oraxen somehow resolved the issue.
I still don't know what was the culprit, but I don't wanna ever deal with that again xD
