### ISSUE TITLE
[BUG] Mining a custom noteblock does not give mining fatigue effect

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1455]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

title

### Steps to reproduce

Mine a custom block

### Plugin Version

2.0-SNAPSHOT

### ProtocolLib Version

5.3.0-SNAPSHOT-723

### Server Software & Version

Paper version 1.21-45-master@4d20922

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
Considering swapping 1.20.5+ to use the new attribute system which fixes more or less all need for schedulers and potion effects
does mean 1.20.4 either has to be dropped or have alternative logic
also logic for calculating break speed needs to be handled which aint too sure on yet, since the base noteblock is hardness 0.8 always and we essentially wanna just change the hardness after calculations been made
