### ISSUE TITLE
Items have no default attributes

### ISSUE THREAD

**Issue by 404forever1** [oraxen/oraxen#1564]

**Comment by Seasonull** [comment]
Please describe the issue you're having in detail. I am not able to duplicate this problem and my default items have attributes if they are of a parent item that should have them. You can turn on/off advanced tooltips in Minecraft with F3+H and in the tooltip you will see what kind of parent item it has.

If this issue is already resolved or there is no response after some time, I will close this ticket. Thank you.

**Comment by 404forever1** [comment]
my qs
