### ISSUE TITLE
Various bugs with custom blocks (using noteblock mechanic, not tested with mushroom method)

### ISSUE THREAD

**Issue by BookWyrm114** [oraxen/oraxen#255]
- placing an item such as a ladder always uses the default rotation, and can be very buggy.
- Due to how interactions with the custom blocks work, water placed on custom blocks works in the nether
- occasionally vanilla blocks can't be placed on custom blocks at all

**Comment by CraftCoderr** [comment]
Why noteblock mechanic is preferred over mushroom? I have found some visual bug with retextured noteblocks, which appears when you break (maybe when place too) under the custom block - model of block resets to noteblock for split second. So it's  looks unnatural. I think this is because Client trying to recalculate state of noteblock, which is depends on type of block under.
I guess mushroom blocks don't have this kind of problem.

**Comment by Th0rgal** [comment]
> * placing an item such as a ladder always uses the default rotation, and can be very buggy.
> * Due to how interactions with the custom blocks work, water placed on custom blocks works in the nether
> * occasionally vanilla blocks can't be placed on custom blocks at all

Alright, I'll work on a fix. Do you have examples of vanilla blocks that can't be placed?

**Comment by Th0rgal** [comment]
> 



> Why noteblock mechanic is preferred over mushroom? I have found some visual bug with retextured noteblocks, which appears when you break (maybe when place too) under the custom block - model of block resets to noteblock for split second. So it's looks unnatural. I think this is because Client trying to recalculate state of noteblock, which is depends on type of block under. I guess mushroom blocks don't have this kind of problem.

Unfortunately mushroom stems do have this kind of problems (and much more) because when you break a mushroom it changes the textures of all mushrooms next to it. Mushroom stems are also quite common in vanilla generation and only provide 64 variations while noteblocks give you about 800.
