### ISSUE TITLE
Oraxen removes Redstone Proximity Sensors default recipe

### ISSUE THREAD

**Issue by Ugleh** [oraxen/Oraxen#26]
I've had issues from a user of my Redstone Proximity Sensor 2.4.9.2 for PaperMC 1.15.2 who also uses Oraxen. I don't know the details but it seems the Oraxen either overwrites or deletes the recipe as shown:

![image](https://user-images.githubusercontent.com/274099/79085994-8d2d7b80-7d08-11ea-9d4f-8d0ffa329329.png)

Does Oraxen provide a recipe like this or is it user error?

**Comment by tim54000** [comment]
Issue reproduced on PaperMC 1.15.2 (git-PAPER-162) with
- RedstoneProximitySensor v2.5.0
- Oraxen (720d67d)
- ProtocolLib v4.5.0 (Not yet tested for MC 1.15.2)

**Errors:**
```[18:53:53 ERROR]: Tried to load unrecognized recipe: redstoneproximitysensor:redstoneproximitysensor removed now.```
![image](https://user-images.githubusercontent.com/8940734/79140669-9d049880-7db8-11ea-9297-77eb0846b5ae.png)

We can see that the recipe is deleted when a player logs in.
However, this error is sent by PaperMC because one of the plugins uses a deprecated API (see [the patch 0074)](https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0074-Display-warning-on-deprecated-recipe-API.patch).

**Also tested:**
- Redstone Proximity Sensors alone, the recipe appears.
- Redstone Proximity Sensors and ProtocolLib, the recipe appears.

**Important**:  *I am not the creator or maintainer of the project.*

**Comment by Ugleh** [comment]
Appreciate you doing more tests for me considering you aren't the one that maintains this project. You mention that it is an error produced by Minecraft server itself but that it works when it is alone, and it works when its with ProtocolLib, so it does show that it has something to do with Oraxen.

Is it my understanding that the resource pack being loaded by Oraxen causes the recipe that RPS is trying to load to fail? Can you tell me what loads first in the scenario where the recipe is not loading, maybe I can do a softdepend on my end to fix the problem?

**Comment by Th0rgal** [comment]
Hey there! Thank you for opening an issue. There is actually a recipes clear done by Oraxen (otherwise recipes reload could not work), see https://github.com/Th0rgal/Oraxen/blob/master/src/main/java/io/th0rgal/oraxen/recipes/RecipesManager.java#L22. This is a bad way to do that but I didn't find something better. A solution could be to add a an option in the configuration of oraxen to disable this recipes clear (and tell to the user that by doing so he would lose the recipes reload feature). This would obviously be a temporary solution until we find something better.

If this seems okay to you, I should add it tomorrow.

**Comment by Ugleh** [comment]
I don't know a better way. I could also do a soft depend, but not sure if that would work. I think in the screenshot above my plugin is loading in second anyways, so clearly that isn't the solution.

Does the reload have to happen on startup of the server? Bukkit.resetRecipes() Just links to console.reload(). Not sure if you followed that breadcrumb in CraftBukkit before. Not quite sure what the end goal is but you could probably get away with
`this.resourcePackRepository.a();`
which is inside the reload command:

`    public void reload() {
        if (!this.isMainThread()) {
            this.execute(this::reload);
        } else {
            this.getPlayerList().savePlayers();
            this.resourcePackRepository.a();
            this.b(this.getWorldServer(DimensionManager.OVERWORLD).getWorldData());
            this.getPlayerList().reload();
            this.bb();
        }
    }`

**Comment by tim54000** [comment]
A temporary patch may suffice, especially since Spigot introduced the [`removeRecipe()`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Server.html#removeRecipe-org.bukkit.NamespacedKey-) method in Spigot 1.15.2. This is surely the best way (using the API).

**Comment by Th0rgal** [comment]
Fixed!
