### ISSUE TITLE
[SUGGESTION] Transparent block with hitbox (custom leaves blocks)

### ISSUE THREAD

**Issue by TeiBri** [oraxen/oraxen#347]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I always needed to do custom trees with custom wood and custom LEAVES. And now, when I know there are rotated blocks, why dont do a custom leaves? Every leaves have a distance. We can change it, but it change generation of a world too. You have to do for every tree to have only 1 distance for one type of leaves. And rest of distances is for custom leaves!
PLEASE!!! DO IT! D: None plugin has it...

### Reason

Because it is good and NONE plugin has it... :D  (*Sorry for my english. Im not using this language.*:-))

**Comment by Boy0000** [comment]
No plugin has custom leaves like that because it just isnt feasable to redo the entire leaf decay system in a plugin.
Adding transparent blocks as an option is doable via the Persistent state or chorus plants, but leaf decay would not be a thing for said blocks. This would require modification to your server itself

But adding transparent blocks without leaf decay will be supported over time
