### ISSUE TITLE
disable normal string

### ISSUE THREAD

**Issue by magicelk235** [oraxen/oraxen#644]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

"disable normal string: true/false" something like this in the settings
if you disable normal string this make you that you can't place normal strings only the custom one

### Reason

the normal string is very buggy, doesn't have texture and it doesn't very useful so why not have this option

**Comment by Boy0000** [comment]
1. doesnt have texture because when stringblock mechanic is enabled ur sacrificing all its functionality
2. It is used in stringblock mechanic to fake 2 tall plants
3. This is such a small thing that you could make in another plugin in 3 lines so no wont add it
4. Having 200 of small changes like this clutters the plugin, when other plugins can easily achieve this
