### ISSUE TITLE
[BUG] can't fixed furniture rotations

### ISSUE THREAD

**Issue by Nolex01** [oraxen/oraxen#699]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

In the title.

### Steps to reproduce

Place a furniture on the wall..
Furniture gets rotated on every single side.. (n, e, s, w)
Done, you can't make a wall lantern for example.

### Plugin Version

1.151.0

### ProtocolLib Version

5

### Server Software & Version

1.19 paper

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by repeater64** [comment]
I am having the same issue, but I realised that OP's description isn't super clear about what exactly the issue is, so I thought I'd clarify.
The issue is that furniture placed on walls should never rotate the item within the item frame. 
Currently, based on the direction the player is facing, the item within the invisible item frame gets rotated.
This makes perfect sense when furniture is aligned to the floor, but when it is on a wall, this just doesn't make any sense. 

For example, here is a clock placed on a wall. The first screenshot was when the player was facing North, and this is how it should always look. The second screenshot was when the player was facing north-west and as you can see the item is rotated.
If the player was facing south the clock would be upside down. etc.

![2023-02-10_22 13 56](https://user-images.githubusercontent.com/62812170/218210932-c383fd8f-a9be-460d-90d4-a22bbba5ae2b.png)
![2023-02-10_22 14 04](https://user-images.githubusercontent.com/62812170/218210948-1ede91f1-5b1a-47a1-8824-3fc266d548e5.png)

**Comment by Boy0000** [comment]
I am wondering if limiting rotation should be done in one of the below ways
1. Always make furniture placed on sides of block have no rotation, aka pointing up
2. Require LimitedPlacing mechanic and walls set to true for it to do so
3. Let you specifically specify `rotation: NONE` in the config again

@repeater64

**Comment by repeater64** [comment]
Personally number one is what I think makes most sense. Out of the 300+ furniture pieces I configured for our server none of them would make sense to be rotated on walls. 

--
  Isaac Riordan Home
  ***@***.***
