### ISSUE TITLE
Iris Developer

### ISSUE THREAD

**Issue by NextdoorPsycho** [oraxen/oraxen#709]
hello, I am the developer for Iris World generator

I told someone to make an issue over here regarding some kind of memory leak or crashing issue

https://github.com/oraxen/oraxen/issues/703

Regardless. After taking a look at the memory dumps for some reason the oraxen blocks are just being overloaded in the cache. I'm not entirely sure if this is the original developer of oraxen but we had a cheeky solution to implementing your blocks into our generator because of how we generate. Have you guys changed your implementation in the past year by chance? And if so, do you happen to have a new documentation for your implementation? If you could provide me with a link or an example, that would be fantastic. I hope to resolve this issue it could be from me using an outdated form of block generation back when we had an archaic solution. Or, if you've changed some thing since then, I can update my dependencies and rework stuff assuming its not on your end. Thank you! Let me know if you have any information regarding that.

**Comment by Boy0000** [comment]
@NextdoorPsycho if all you need is the blockdata that is tied to an ID, use 
```java
OraxenBlocks.getOraxenBlockData(itemID)
```
https://github.com/oraxen/oraxen/blob/master/src/main/java/io/th0rgal/oraxen/api/OraxenBlocks.java

This will work for both StringBlockMechanic and NoteBlockMechanic
The old BlockMechanic that uses mushroom blocks is not counted here as its essentially deprecated
When looking at ur code yeah seemed like u used a build of oraxen from August 2021, a ton of stuff has changed since then (v1.94.0)

All latest builds should be accessible via Jitpack. gradle info can be found [here](https://docs.oraxen.com/developers/api#jitpack)
Feel free to reply here, or DM me on Discord / the server, Boy#8008 if you need more info
