### ISSUE TITLE
[BUG] Atlas generation causes some issues for some players

### ISSUE THREAD

**Issue by Taiyou06** [oraxen/oraxen#753]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

this post is a reminder for atlas generation toggle option for directory or sprite based generation

### Steps to reproduce

https://mclo.gs/OHXforI

### Plugin Version

1.153.0

### ProtocolLib Version

5.0

### Server Software & Version

Current: git-Purpur-1927 (MC: 1.19.3)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
this isnt an issue with the generation but rather ur packl containing one or more files that break formatting rules
1.153.3 adds a debugger to find out which, but your client log will also tell you
Directory works here because it just lets MC handle it and doesnt just add every single sprite
But that also breaks mip levels

First check ur clientlog and make sure u abide by resourcepack formatting rules
I'll still add the optiuon but i wouldnt suggest using Directory over Sprite @Taiyou06

**Comment by Taiyou06** [comment]
okay so update to this problem: i was able to reproduce it (somehow?) and it was caused by HappyHud's font. it was pointing out to non existent texture which it was causing this bug. 

This log contains with HH files and HH files deleted https://mclo.gs/ZlpONOs

**Comment by Boy0000** [comment]
That would be why, either HH isnt correctly copying everything OR if you manually imported it you did not manually import it correctly

**Comment by Taiyou06** [comment]
im using it's built in copy-resourcepack thingy

**Comment by Taiyou06** [comment]
yeah reported to HH dev all good. ty for your time boy
