### ISSUE TITLE
[BUG] "energyblast" Mechanic

### ISSUE THREAD

**Issue by Chiefink5** [oraxen/oraxen#845]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

after adding the energyblast mechanic to my config for a sword, (everything is spaced correctly and no caps where they're not supposed to be) but the mechanic isn't working at all. Boy said it could be from adding the protection checks in one of the updates

### Steps to reproduce

configure the energyblast mechanic on an item and see that the right click produces no blast of energy :)

### Plugin Version

1.156.2

### ProtocolLib Version

5.1.0-SNAPSHOT-645

### Server Software & Version

1.18.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by ImDarkLaw** [comment]
Complementary to the report above, it's safe to say that i'm experiencing the same issue while using Oraxen **version 1.156.2** when trying to use **Energy Blast** mechanic.

### Server Software & Version Info
- [Server Software: git-Purpur-1976 (MC: 1.19.4)](https://purpurmc.org/downloads)
- [ProtocolLib version 5.0.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/5.0.0)
- [WorldGuard version 7.0.8-beta-01+cbb2ba7](https://enginehub.org/worldguard#downloads)
- [GriefPrevention version 16.18.1](https://dev.bukkit.org/projects/grief-prevention/files/4433061)
- [Essentials version 2.20.1-dev+7-646b60a](https://essentialsx.net/downloads.html)

### Plugins List
https://pastes.dev/sr8Pf1ASI7

### Description & how to reproduce
- #### Use Paper or Purpur as the server software on 1.19.4
- #### Install Oraxen, ProtocolLib, EssentialsX, WorldGuard, GriefPrevention.
- #### Copy the oraxen item from https://pastes.dev/6zbwyTBeSF into one of your items ymls (plugins/Oraxen/items/testitem.yml).
- #### Grab the item from the oraxen inventory or the /o give command.
- #### Try to use the ability on a __global__ region with no flags set as well as on an unclaimed land. (you can check, by default, using a stick for GriefPrevention claims which by default you shouldn't have any regardless)
- #### Notice that the Energy Blast ability does not *go through*.

### Additional Information
- No errors and/or warnings relevant to Oraxen or any of its dependencies.
- Only applicable ever since the 1.156.0 update came out.
- Tests done on Purpur server behind a velocity proxy.
- Not game breaking, but ruins the Energy Blast mechanic and, thus, any items that utilize it.
